import { RotateCcw } from 'lucide-react'
import { useMemo } from 'react'
import { formatPrice } from '../../lib/format'
import { analytics } from '../../services/analyticsService'
import { orderService } from '../../services/orderService'
import { storage } from '../../services/storage'
import { useLoyalty } from '../../store/LoyaltyContext'
import { useUI } from '../../store/UIContext'
import { Button } from '../ui/Button'
import { Sheet } from '../ui/Sheet'
import { VALUE_PILLARS } from './valuePillars'

/**
 * "للمدير" — explains the business value in under a minute and shows live
 * numbers generated by whatever was done during the demo.
 */
export function ManagerSheet() {
  const { managerOpen, setManagerOpen } = useUI()
  const { state } = useLoyalty()

  const stats = useMemo(() => {
    if (!managerOpen) return null
    const orders = orderService.list()
    const s = analytics.get()
    const revenue = orders.reduce((sum, o) => sum + o.total, 0)
    const upsellRevenue = orders.reduce((sum, o) => sum + o.upsellRevenue, 0)
    const aov = orders.length ? revenue / orders.length : 0
    const aovWithout = orders.length ? (revenue - upsellRevenue) / orders.length : 0
    return {
      orders: orders.length,
      aov,
      uplift: aovWithout ? ((aov - aovWithout) / aovWithout) * 100 : 0,
      acceptance: s.upsellShown ? Math.round((s.upsellAccepted / s.upsellShown) * 100) : 0,
      upsellRevenue,
      views3d: s.productViews3d,
    }
  }, [managerOpen])

  if (!managerOpen || !stats) return null

  return (
    <Sheet open onClose={() => setManagerOpen(false)} title="لماذا هذا النظام؟">
      <div className="space-y-5 px-5 pb-safe">
        <p className="text-sm leading-relaxed text-ink-soft">
          هذا ليس مجرد منيو إلكتروني — إنه نظام رقمي يساعد سنمار على زيادة المبيعات وعودة العملاء.
        </p>

        <ul className="space-y-2.5">
          {VALUE_PILLARS.map((p, i) => (
            <li key={p.title} className="flex animate-fade-up gap-3 rounded-2xl bg-white p-3.5 shadow-card" style={{ animationDelay: `${i * 60}ms` }}>
              <span className="grid size-11 shrink-0 place-items-center rounded-xl bg-sand text-2xl">{p.emoji}</span>
              <span>
                <span className="block font-display font-bold">{p.title}</span>
                <span className="block text-xs leading-relaxed text-muted">{p.text}</span>
              </span>
            </li>
          ))}
        </ul>

        <section>
          <h3 className="mb-2 font-display font-bold">📊 أرقام هذه التجربة (مباشرة)</h3>
          <div className="grid grid-cols-2 gap-2.5">
            <Stat label="طلبات مؤكدة" value={String(stats.orders)} />
            <Stat label="متوسط قيمة الطلب" value={formatPrice(Math.round(stats.aov))} />
            <Stat
              label="أثر الاقتراحات على المتوسط"
              value={stats.uplift ? `+${Math.round(stats.uplift)}%` : '—'}
              highlight
            />
            <Stat label="قبول الاقتراحات" value={`${stats.acceptance}%`} />
            <Stat label="إيراد من الاقتراحات" value={formatPrice(stats.upsellRevenue)} />
            <Stat label="مشاهدات 3D" value={String(stats.views3d)} />
            <Stat label="بطاقة الولاء" value={`${state.stamps} / ${state.goal}`} />
            <Stat label="مكافآت مستخدمة" value={String(state.rewardsRedeemed)} />
          </div>
          <p className="mt-2 text-[11px] leading-relaxed text-muted">
            الأرقام محسوبة من تفاعلك في هذا العرض فقط (بيانات تجريبية محفوظة على هذا الجهاز). في النسخة الكاملة تُربط بنظام نقاط البيع.
          </p>
        </section>

        <div className="rounded-2xl bg-sand/70 p-4 text-xs leading-relaxed text-ink-soft">
          <p className="mb-1 font-bold text-ink">المرحلة القادمة (بعد الموافقة):</p>
          ربط الطلبات بالكاشير • تسجيل العميل برقم الجوال • لوحة تحكم للعروض والأسعار • تقارير أسبوعية.
        </div>

        <Button
          variant="soft"
          block
          icon={<RotateCcw className="size-4" />}
          onClick={() => {
            storage.clearAll()
            window.location.hash = '#/scan'
            window.location.reload()
          }}
        >
          إعادة ضبط العرض (ابدأ من جديد)
        </Button>
        <div className="h-2" />
      </div>
    </Sheet>
  )
}

function Stat({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) {
  return (
    <div className={highlight ? 'rounded-2xl bg-leaf-soft p-3' : 'rounded-2xl bg-white p-3 shadow-card'}>
      <p className="text-[11px] text-muted">{label}</p>
      <p className={highlight ? 'font-display text-xl font-extrabold text-leaf' : 'font-display text-xl font-extrabold'}>{value}</p>
    </div>
  )
}
